///|/ Copyright (c) SuperSlicer 2018 - 2025 Durand Rémi @supermerill
///|/ Copyright (c) Prusa Research 2016 - 2023 Pavel Mikuš @Godrak, Vojtěch Bubník @bubnikv, Lukáš Hejl @hejllukas, Lukáš Matěna @lukasmatena
///|/ Copyright (c) Slic3r 2014 - 2015 Alessandro Ranellucci @alranel
///|/ Copyright (c) 2015 Maksim Derbasov @ntfshard
///|/
///|/ ported from lib/Slic3r/Layer.pm:
///|/ Copyright (c) Prusa Research 2016 - 2022 Vojtěch Bubník @bubnikv
///|/ Copyright (c) Slic3r 2011 - 2016 Alessandro Ranellucci @alranel
///|/
///|/ SuperSlicer, PrusaSlicer, Slic3r are released under the terms of the AGPLv3 or higher
///|/
#ifndef slic3r_Layer_hpp_
#define slic3r_Layer_hpp_

#include "Line.hpp"
#include "libslic3r.h"
#include "BoundingBox.hpp"
#include "Flow.hpp"
#include "SurfaceCollection.hpp"
#include "ExtrusionEntityCollection.hpp"

#include <boost/container/small_vector.hpp>

namespace Slic3r {

class ExPolygon;
using ExPolygons = std::vector<ExPolygon>;
class Layer;
using LayerPtrs = std::vector<Layer*>;
class LayerSliceIsland;
class LayerRegionIsland;
class LayerRegion;
using LayerRegionPtrs = std::vector<LayerRegion*>;
using LayerRegionSetConstPtrs = std::set<const LayerRegion*>;
class PrintRegion;
class PrintObject;

namespace FillAdaptive {
    struct Octree;
}

namespace FillLightning {
    class Generator;
};

class LayerRegion
{
public:
    [[nodiscard]] Layer*                            layer()         { return m_layer; }
    [[nodiscard]] const Layer*                      layer() const   { return m_layer; }
    [[nodiscard]] const PrintRegion&                region() const  { return *m_region; }

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    [[nodiscard]] const SurfaceCollection&          slices() const { /*assert(surfaces_filled);*/ return m_slices; }
    bool                                            has_slices() const { return m_slices.empty(); }

    //// Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    //// note: if empty, that means there is no overlap, so you don't need to intersect with it.

    [[nodiscard]] const ExPolygons&                 fill_no_overlap_expolygons() const { return m_fill_no_overlap_expolygons; }

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    [[nodiscard]] const SurfaceCollection&          fill_surfaces() const { return m_fill_surfaces; }
    [[nodiscard]] SurfaceCollection&                set_fill_surfaces() { return m_fill_surfaces; }
    
    // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    // computed from islands. use islands if it's easier for you.
    [[nodiscard]] const ExPolygons&                 fill_expolygons() const;

private:
    mutable uint64_t m_cache_fill_expolygons_computed = 0;
    mutable ExPolygons m_cache_fill_expolygons;
    // create my fill_expolygons from all islands that reference me.
    ExPolygons                                     _compute_fill_expolygons() const;

public:
    // collection of polylines representing the unsupported bridge edges
    [[nodiscard]] const Polylines&                  unsupported_bridge_edges() const { return m_unsupported_bridge_edges; }

    void     clear();

    Flow     flow(FlowRole role) const;
    Flow     flow(FlowRole role, double layer_height) const;
    double   bridging_height_avg_mm() const;
    Flow     bridging_flow(FlowRole role, BridgeType force_type = BridgeType::btNone) const;

    void    slices_to_fill_surfaces_clipped(coord_t opening_offset);
    void    prepare_fill_surfaces();

    void    process_external_surfaces(const Layer *lower_layer, const Polygons *lower_layer_covered);
    void    process_external_surfaces_old(const Layer *lower_layer, const Polygons *lower_layer_covered);
    double  infill_area_threshold() const;
    // Trim surfaces by trimming polygons. Used by the elephant foot compensation at the 1st layer.
    void    trim_surfaces(const Polygons &trimming_polygons);
    // Single elephant foot compensation step, used by the elephant foor compensation at the 1st layer.
    // Trim surfaces by trimming polygons (shrunk by an elephant foot compensation step), but don't shrink narrow parts so much that no perimeter would fit.
    void    elephant_foot_compensation_step(const float elephant_foot_compensation_perimeter_step, const Polygons &trimming_polygons);

    void    export_region_slices_to_svg(const char *path) const;
    void    export_region_fill_surfaces_to_svg(const char *path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void    export_region_slices_to_svg_debug(const char *name) const;
    void    export_region_fill_surfaces_to_svg_debug(const char *name) const;

    const ExPolygons &get_raw_slices() const { return m_raw_slices; }
    const ExPolygons &get_raw_bounding_box() const { return m_raw_slices; }
    void set_raw_slices(ExPolygons&& raw_slices) { m_raw_slices = std::move(raw_slices); }

protected:
    friend class Layer;
    friend class PrintObject;

    LayerRegion(Layer *layer, const PrintRegion *region) : m_layer(layer), m_region(region) {}
    ~LayerRegion() = default;

private:
    // Modifying m_slices
    friend std::string fix_slicing_errors(LayerPtrs&, const std::function<void()>&);
    template<typename ThrowOnCancel>
    friend void apply_mm_segmentation(PrintObject& print_object, ThrowOnCancel throw_on_cancel);

    Layer                      *m_layer;
    const PrintRegion          *m_region;

    // Backed up slices before they are split into top/bottom/internal.
    // Only backed up for multi-region layers or layers with elephant foot compensation.
    //FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    // superslicer -> layer_needs_raw_backup is now true, so evryone has their cache here.
    ExPolygons                  m_raw_slices;

//FIXME make m_slices public for unit tests
public:
    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    // TODO: separate them per island.
    SurfaceCollection           m_slices;
#if _DEBUG
    bool                        surfaces_filled = false;
#endif
private:
    //// Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    //// note: never empty.
    ExPolygons                  m_fill_no_overlap_expolygons;

    // Collection of surfaces for infill generation, created by splitting m_slices by m_fill_expolygons.
    SurfaceCollection           m_fill_surfaces;

    // collection of polylines representing the unsupported bridge edges
    Polylines                   m_unsupported_bridge_edges;
};

//// One LayerIsland may be filled with solid fill, sparse fill, top / bottom fill.
//static constexpr const size_t LayerExtrusionRangesStaticSize = 3;
//using LayerExtrusionRanges =
//#ifdef NDEBUG
//    // To reduce memory allocation in release mode.
//    boost::container::small_vector<LayerExtrusionRange, LayerExtrusionRangesStaticSize>;
//#else // NDEBUG
//    // To ease debugging.
//    std::vector<LayerExtrusionRange>;
//#endif // NDEBUG

// LayerSlice contains one or more LayerIsland objects,
// each LayerIsland containing a set of perimeter extrusions extruded with one particular PrintRegionConfig parameters
// and one or multiple 
// kind of similar as old's LayerIsland
class LayerRegionIsland
{
private:
    friend class Layer;
    //// 0-based extruder, -1 => not set yet (any).
    //// when the LayerRegionIsland will be sorted, if one has infill & peri extrusion with != extruder,
    ////  then it will split into two.
    uint16_t m_extruder_id = uint16_t(-1);

    std::map<ExtrusionRole, ExtrusionEntityCollection> m_extrusion_regions;
    // my regions
    LayerRegionSetConstPtrs m_regions;
public:
    // if true, then can be used by any extruder for wiping.
    bool can_be_used_to_wipe = false;

    //LayerRegionIsland(const LayerRegionSetConstPtrs &regions) : m_regions(regions) {}
    LayerRegionIsland(const LayerRegionSetConstPtrs &regions, uint16_t extruder_id) : m_regions(regions), m_extruder_id(extruder_id) {}

    static inline ExtrusionRole PERIMETERS = ExtrusionRole::Perimeter;
    static inline ExtrusionRole GAP_FILLS = ExtrusionRole::GapFill;
    static inline ExtrusionRole INFILLS = ERM_Infill;
    static inline ExtrusionRole IRONINGS = ExtrusionRole::Ironing;
    static inline ExtrusionRole MILLS = ExtrusionRole::Milling;
    static inline ExtrusionRole SUPPORT = ExtrusionRole::SupportMaterial;
    static inline ExtrusionRole SUPPORT_INTERFACE = ExtrusionRole::SupportMaterialInterface;


    bool has_extrusion(ExtrusionRole role) const {
        auto it = m_extrusion_regions.find(role);
        if(it == m_extrusion_regions.end()) return false;
        return !it->second.empty();
    }
    bool has_extrusions() const;
    const ExtrusionEntityCollection &extrusion(ExtrusionRole role) const {
        assert(has_extrusion(role));
        return m_extrusion_regions.at(role);
    }

    void remove_empty_extrusions();

    ExtrusionEntityCollection & mutable_extrusion(ExtrusionRole role) {
        return m_extrusion_regions[role];
    }

    const LayerRegionSetConstPtrs &regions() const { return m_regions; }

    void simplify_extrusion_entity(const Layer& layer);

    uint16_t extruder_id() const { return m_extruder_id; };

};

using LayerRegionIslandPtr = std::unique_ptr<LayerRegionIsland>;

// kind of similar as old's LayerSlice
class LayerSliceIsland
{
public:
    // only filled when Layer's LayerSliceIsland are locked.
    // used by supportspotgenerator (badly)
    struct Link
    {
        LayerSliceIsland* to;
        float area;
    };
    std::vector<Link> overlaps_above;
    std::vector<Link> overlaps_below;

    const ExPolygons &get_perimeter_slices() { return m_perimeter_slices; }

protected:
    ExPolygon m_slice;
    BoundingBox m_bbox;
    // only regions that are relevant for this island
    LayerRegionSetConstPtrs m_regions;
    // storing unique_ptr because it's easier to have consistent objects while manipulating the vector.
    std::vector<LayerRegionIslandPtr> m_extrusions;
    // cache, can be accessed via m_regions. Only set after fill_regions.
    Layer *m_layer = nullptr;

    // Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    // note: if empty, that means there is no overlap, so you don't need to intersect with it.
    ExPolygons                  m_fill_no_overlap_expolygons;
    ExPolygons                  m_fill_expolygons;
    BoundingBoxes               m_fill_expolygons_bboxes;
    // to get the boundary in avoid_crossing_perimeters. Filled by make_perimeters()
    ExPolygons                  m_perimeter_slices;

public:

    LayerSliceIsland(const ExPolygon &slice);
    void fill_regions(Layer& layer);

    ExPolygon &get_mutable_slice() { return m_slice; }
    const ExPolygon &get_slice() const { return m_slice; }
    const BoundingBox &get_bounding_box() const { return m_bbox; }
    const LayerRegionSetConstPtrs &regions() const { return m_regions; }
    const std::vector<LayerRegionIslandPtr> &regions_islands() const { return m_extrusions; }
    std::vector<LayerRegionIslandPtr> &regions_islands()  { return m_extrusions; }

    LayerRegionIsland& get_or_add_region_island(const LayerRegionSetConstPtrs &regions, uint16_t extruder_id = uint16_t(-1));
    LayerRegionIsland& add_new_region_island(const LayerRegionSetConstPtrs &regions, uint16_t extruder_id = uint16_t(-1));

        // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    [[nodiscard]] const ExPolygons&                 fill_expolygons() const { return m_fill_expolygons; }
    // and their bounding boxes
    [[nodiscard]] const BoundingBoxes&              fill_expolygons_bboxes() const { return m_fill_expolygons_bboxes; }

    // return true if this expolygon is (inside) this island.
    // TODO remove when the fill surfaces will be linked to their islands (maybe moved here)
    bool is_expolygons_from_region(const ExPolygon &expolygon) const;

    // Is there any valid extrusion assigned to one LayerRegionIslandPtr?
    bool has_extrusions() const;

    //// Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    //// note: if empty, that means there is no overlap, so you don't need to intersect with it.
    [[nodiscard]] const ExPolygons&                 fill_no_overlap_expolygons() const { return m_fill_no_overlap_expolygons; }

    void make_perimeters(LayerRegionIsland &region_island);
};
using LayerSliceIslandPtr = std::unique_ptr<LayerSliceIsland>;

//static constexpr const size_t LayerIslandsStaticSize = 1;
//using LayerIslands =
//#ifdef NDEBUG
//    // To reduce memory allocation in release mode.
//    boost::container::small_vector<LayerIsland, LayerIslandsStaticSize>;
//#else // NDEBUG
//    // To ease debugging.
//    std::vector<LayerIsland>;
//#endif // NDEBUG

class Layer 
{
    coord_t             m_height;        // layer height
    coord_t             m_print_z;       // Z used for printing
public:
    // Sequential index of this layer in PrintObject::m_layers, offsetted by the number of raft layers.
    size_t              id() const          { return m_id; }
    void                set_id(size_t id)   { m_id = id; }
    PrintObject*        object()            { return m_object; }
    const PrintObject*  object() const      { return m_object; }

    Layer              *upper_layer;
    Layer              *lower_layer;
//    bool                slicing_errors;
    // heights
    static coord_t      scale_to_layer_coord(double z);
    double              slice_z;       // Z used for slicing, in unscaled coordinates
    coord_t             scaled_print_z() const { assert(scale_to_layer_coord(unscaled(m_print_z)) == m_print_z); return m_print_z; }
    double              unscaled_print_z() const { assert(scale_to_layer_coord(unscaled(m_print_z)) == m_print_z); return unscaled(m_print_z); }
    coord_t             scaled_height() const { return m_height; }
    double              unscaled_height() const { return unscaled(m_height); }
    coord_t             scaled_bottom_z() const { return this->m_print_z - this->m_height; }


    //Extrusions estimated to be seriously malformed, estimated during "Estimating curled extrusions" step. These lines should be avoided during fast travels.
    //TODO: put in island
    CurledLines         curled_lines;

protected:
    // geometric island.
    // Collection of expolygons generated by slicing the possibly multiple meshes of the source geometry 
    // (with possibly differing extruder ID and slicing parameters) and merged.
    // For the first layer, if the Elephant foot compensation is applied, this lslice is uncompensated, therefore
    // it includes the Elephant foot effect, thus it corresponds to the shape of the printed 1st layer.
    // These lslices are also used to detect overhangs and overlaps between successive layers, therefore it is important
    // that the lslice is not compensated by the Elephant foot compensation algorithm.
    ExPolygons              m_lslices; // now in LayerSliceIsland, here is just a cache for quicker lslices()
    // in unique_ptr to be sure the address doesn't change when updating the vector.
    std::vector<LayerSliceIslandPtr> m_islands;
    bool m_islands_locked = false;

public:
    // shortcut to get slices stored in islands
    const ExPolygons &      lslices() const { return m_lslices; }

    void set_islands(ExPolygons && new_islands);
    const std::vector<LayerSliceIslandPtr> &islands() const { return m_islands; }
    LayerSliceIsland& get_mutable_island(size_t idx) { return *m_islands[idx]; }
    // to be called after LayerRegion's m_slices are created (but still not separated)
    // create surfaces in layerregion, and fill regionislands.
    void add_regions_to_islands();

    size_t                  region_count() const { return m_regions.size(); }
    const LayerRegion*      get_region(size_t idx) const { return m_regions[idx]; }
    LayerRegion*            get_region(size_t idx) { return m_regions[idx]; }
    LayerRegion*            add_region(const PrintRegion *print_region);
    const LayerRegionPtrs&  regions() const { return m_regions; }
    // Test whether whether there are any slices assigned to this layer.
    bool                    empty() const;    
    void                    make_slices();
    // After creating the slices on all layers, chain the islands overlapping in Z.
    static void             build_up_down_graph(Layer &below, Layer &above);
    // erase LayerRegion's 'slices' surfaces and recreate one from raw
    void                    restore_untyped_slices();
    // Slices merged into islands, to be used by the elephant foot compensation to trim the individual surfaces with the shrunk merged slices.
    ExPolygons              merged(coordf_t offset_scaled = 0) const;
    void                    make_perimeters();
    void                    make_milling_post_process();
    void                    make_fills(FillAdaptive::Octree     *adaptive_fill_octree,
                                       FillAdaptive::Octree     *support_fill_octree,
                                       FillLightning::Generator *lightning_generator);
    void                    make_ironing();
    Polylines               generate_sparse_infill_polylines_for_anchoring(FillAdaptive::Octree *adaptive_fill_octree,
                                                                           FillAdaptive::Octree *support_fill_octree,
                                                                           FillLightning::Generator* lightning_generator) const;


protected:
    void _make_fills(LayerSliceIsland &island,
                     FillAdaptive::Octree *adaptive_fill_octree,
                     FillAdaptive::Octree *support_fill_octree,
                     FillLightning::Generator *lightning_generator);
    void                    _make_ironing(LayerSliceIsland &island);
    Polylines               _generate_sparse_infill_polylines_for_anchoring(const LayerSliceIsland &island,
                                                                           FillAdaptive::Octree *adaptive_fill_octree,
                                                                           FillAdaptive::Octree *support_fill_octree,
                                                                           FillLightning::Generator* lightning_generator) const;

public:

    void                    export_region_slices_to_svg(const char *path) const;
    void                    export_region_fill_surfaces_to_svg(const char *path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void                    export_region_slices_to_svg_debug(const char *name) const;
    void                    export_region_fill_surfaces_to_svg_debug(const char *name) const;

    // Is there any valid extrusion assigned to any island-region?
    bool            has_extrusions() const;

    void simplify_extrusion_path() {
        for (LayerSliceIslandPtr &island_ptr : m_islands)
            for (LayerRegionIslandPtr &regisland : island_ptr->regions_islands())
                regisland->simplify_extrusion_entity(*this);
    }

protected:
    friend class PrintObject;
    friend std::vector<Layer*> new_layers(PrintObject*, const std::vector<coordf_t>&);
    friend std::string fix_slicing_errors(LayerPtrs&, const std::function<void()>&);

    Layer(size_t id, PrintObject *object, coord_t height, coord_t print_z, double slice_z, bool scaledok) :
        upper_layer(nullptr), lower_layer(nullptr), 
        //slicing_errors(false),
        slice_z(slice_z), m_print_z(print_z), m_height(height),
        m_id(id), m_object(object) {
        assert(print_z > 100);
        assert(height > 100);
        assert(scale_to_layer_coord(unscaled(print_z)) == print_z);
    }
    virtual ~Layer();
    // Clear fill extrusions, remove them from layer islands.
    void clear_fills();

private:
    // Sequential index of layer, 0-based, offsetted by number of raft layers.
    size_t              m_id;
    PrintObject        *m_object;
    LayerRegionPtrs     m_regions;
};

class SupportLayer : public Layer 
{
public:

    // Zero based index of an interface layer, used for alternating direction of interface / contact layers.
    size_t                      interface_id() const { return m_interface_id; }

    ExtrusionRole role() const;

    void simplify_support_extrusion_path();
protected:
    friend class PrintObject;

    // The constructor has been made public to be able to insert additional support layers for the skirt or a wipe tower
    // between the raft and the object first layer.
    SupportLayer(size_t id, size_t interface_id, PrintObject *object, coord_t height, coord_t print_z, double slice_z, bool scaledok) :
        Layer(id, object, height, print_z, slice_z, scaledok), m_interface_id(interface_id) {}
    virtual ~SupportLayer() = default;

    size_t m_interface_id;
};

template<typename LayerContainer>
inline std::vector<float> slice_z_from_layers(const LayerContainer &layers)
{
    std::vector<float> zs;
    zs.reserve(layers.size());
    for (const Layer *l : layers)
        zs.emplace_back((float)l->slice_z);
    return zs;
}

extern BoundingBox get_extents(const LayerRegion &layer_region);
extern BoundingBox get_extents(const LayerRegionPtrs &layer_regions);

}

#endif
