name: C/C++ Release candidate macos

on:
  push:
    branches:
      - rc

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'rc'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -dsi
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_macos.tar
        path: build/${{ github.event.repository.name }}.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_macos.dmg
        path: build/${{ github.event.repository.name }}.dmg
