name: Ubuntu nightly and release candidate v2

on:
  push:
    branches:
      - Nigthly
      - nightly_dev
      - nightly_master
      - nightly_ubuntu
      - nightly_2.7.63
      - debug_ubuntu
      - beta
      - stable
      - rc
      - beta-rc
      - stable-rc
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  nightly-gtk2:
    if: github.ref_type == 'branch' && contains(fromJSON('["Nigthly","nightly_dev","nightly_master","debug_ubuntu"]'), github.ref_name)
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: nightly_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
      build_args: g
      gtk_package: libgtk2.0-dev
      gtk_version: '2'
      tgz_artifact_name: nightly_${{ github.event.repository.name }}-linux-x64-GTK2.tgz
  nightly-gtk3:
    if: github.ref_type == 'branch' && contains(fromJSON('["Nigthly","nightly_dev","nightly_master","nightly_ubuntu","nightly_2.7.63","debug_ubuntu","beta","stable"]'), github.ref_name)
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: nightly_${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
      build_args: ''
      gtk_package: libgtk-3-dev
      gtk_version: '3'
      tgz_artifact_name: nightly_${{ github.event.repository.name }}-linux-x64-GTK3.tgz
  debug-gtk2:
    if: github.ref_name == 'debug_ubuntu'
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: debug_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
      build_args: bg
      gtk_package: libgtk2.0-dev
      gtk_version: '2'
      tgz_artifact_name: debug_${{ github.event.repository.name }}-linux-x64-GTK2.tgz
  rc-gtk2:
    if: github.ref_name == 'rc'
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: rc_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
      build_args: g
      date_version: false
      gtk_package: libgtk2.0-dev
      gtk_version: '2'
      tgz_artifact_name: rc_${{ github.event.repository.name }}-linux-x64-GTK2.tgz
  rc-gtk3:
    if: github.ref_type == 'branch' && contains(fromJSON('["rc","beta-rc","stable-rc"]'), github.ref_name)
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: rc_${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
      build_args: ''
      date_version: false
      gtk_package: libgtk-3-dev
      gtk_version: '3'
      tgz_artifact_name: rc_${{ github.event.repository.name }}-linux-x64-GTK3.tgz
  release-gtk3:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
      build_args: ''
      date_version: false
      gtk_package: libgtk-3-dev
      gtk_version: '3'
      tgz_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK3.tgz
  release-gtk2:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/build_ubuntu.yml
    with:
      appimage_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
      build_args: g
      date_version: false
      gtk_package: libgtk2.0-dev
      gtk_version: '2'
      tgz_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK2.tgz
  sign-release-gtk3:
    if: github.ref_type == 'tag'
    needs: release-gtk3
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/sign_ubuntu.yml
    with:
      enabled: true
      appimage_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK3.AppImage
      signed_artifact_name: signed_${{ github.event.repository.name }}-linux-x64-GTK3
      tgz_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK3.tgz
  sign-release-gtk2:
    if: github.ref_type == 'tag'
    needs: release-gtk2
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/sign_ubuntu.yml
    with:
      enabled: true
      appimage_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK2.AppImage
      signed_artifact_name: signed_${{ github.event.repository.name }}-linux-x64-GTK2
      tgz_artifact_name: release_${{ github.event.repository.name }}-linux-x64-GTK2.tgz